### ISSUE TITLE
Setting up github pages

### ISSUE THREAD

**Issue by aniket-kes** [adrianhajdin/project_web3.0#105]
My project is working well and good but i want this project to be on github pages i tried usual approach like adding "Homepage" as well as "predeploy" and "Deploy" but it haven't worked for me, can someone give me insights on this issue, it will be really helpful.

**Comment by BrightTNut** [comment]
I think you are asking to adding your file in github , so you need to run command of adding file in git hub repo 
the command like git init, git commit, etc

**Comment by aniket-kes** [comment]
I've already created repo and pushed both the folders but now i want to deploy it to gh pages because it's free and i don't wanna buy hosting platform like hostinger.

**Comment by BrightTNut** [comment]
I also tried this but my pages also not hosted I think we need to buy first domain for hosting page using  github

**Comment by aniket-kes** [comment]
okay i have published it on netlify for free, You can also try it, you just need to upload dist folder and that's it.
p.s. Use Chrome browser , i was facing many issues when i was doing it with brave  so it is better to use chrome.

**Comment by BrightTNut** [comment]
okay
