### ISSUE TITLE
error :  TransactionContext.jsx

### ISSUE THREAD

**Issue by sabarinathan145** [adrianhajdin/project_web3.0#11]
Uncaught (in promise) Error: No ethereum object

at checkIfTransactionsExists (:3000/src/context/TransactionContext.jsx:98:13)

![image](https://user-images.githubusercontent.com/68042285/148685849-bc5fa628-fdb2-4423-8b37-852ffd2eb9d0.png)

I don't Know why it is happening

![image](https://user-images.githubusercontent.com/68042285/148685920-4e21eff9-5655-4ec4-9ba6-c0b2895b519d.png)

**Comment by sabarinathan145** [comment]
I don't Know why it is happening

![image](https://user-images.githubusercontent.com/68042285/148685920-4e21eff9-5655-4ec4-9ba6-c0b2895b519d.png)

**Comment by darismathew92** [comment]
Try re-running. I got solved after some try.

**Comment by sabarinathan145** [comment]
Here I resolve this error by

correcting my smart_contract deploy.js

and finally there was an correction over on my contract_address

**Comment by harleauxcarrera** [comment]
What changed in deploy.js to get this working? @sabarinathan145

**Comment by Gendalf01** [comment]
How did you solve it guys in deploy.js or where?

**Comment by Jmarvin-12** [comment]
> Here I resolve this error by
> 
> correcting my smart_contract deploy.js
> 
> and finally there was an correction over on my contract_address

How? What corrections did you do? @sabarinathan145
