### ISSUE TITLE
Issue in Welcome.jsx file

### ISSUE THREAD

**Issue by akgupta-47** [adrianhajdin/project_web3.0#12]
The issue is in line 38 of Welcome.jsx file
the line given is 
`<div className="flex mf:flex-row flex-col items-start justify-between md:p-20 py-12 px-4">`
here it says mf:flex-row
instead it should be
`<div className="flex md:flex-row flex-col items-start justify-between md:p-20 py-12 px-4">`
otherwise the etherium card won't lineup correctly with in horizontal fashion and would stay in a flex column state that is below connect wallet button in every viewpoint.
A similar mistake of writing mf instead of md is being made in line numbers 39 and 77

**Comment by HimashaHerath** [comment]
when I do this it solved the error of eth card being lined up horizontaly but now in tablet view the eth card and other components in welcome page kind of misplaces
