### ISSUE TITLE
No ethereum object at connectWallet

### ISSUE THREAD

**Issue by darismathew92** [adrianhajdin/project_web3.0#14]
![Screenshot 2022-01-11 034349](https://user-images.githubusercontent.com/78974902/148847524-c239a37f-5955-401f-9a02-ec514bdd7c05.png)
![Screenshot 2022-01-11 034220](https://user-images.githubusercontent.com/78974902/148847574-7d0377ce-324b-477e-a2bb-03364ac284ee.png)

**Comment by darismathew92** [comment]
I got solved after re running it

**Comment by Jyotishmoy12** [comment]
how did you solve this plss help !!!
