### ISSUE TITLE
Error: No Ethereum Object

### ISSUE THREAD

**Issue by alexandregabriel** [adrianhajdin/project_web3.0#32]
I was following the tutorial but I found the following error: 

`ReferenceError: Cannot access 'transactionContract' before initialization
    at getEthereumContract (TransactionContext.jsx:13:89)`

Can anyone help me?

**Comment by alexandregabriel** [comment]
Solved.

**Comment by CRodz13** [comment]
thats it?  "Solved".  Cant follow with how to fixed it?  Thanks.
