### ISSUE TITLE
Private key

### ISSUE THREAD

**Issue by lorenzosyku** [adrianhajdin/project_web3.0#4]
Hey man great tutorial as always, I was just wondering how would you store your private key in a more safe way, because right now everyone can see it 😅 do you think an env file would be a good idea?

**Comment by rhysjson** [comment]
> Hey man great tutorial as always, I was just wondering how would you store your private key in a more safe way, because right now everyone can see it 😅 do you think an env file would be a good idea?

Hey bro, I'd deffo advise using an env file! It's wild that it's currently available in the repo. 

If you get round to it, perhaps open a PR?  Cheers!

**Comment by lorenzosyku** [comment]
Anyway great job man, congrats🎊.
