### ISSUE TITLE
Unable to find the commad to install the dependencies of package.json.. plss help!!

### ISSUE THREAD

**Issue by Jyotishmoy12** [adrianhajdin/project_web3.0#68]

**Comment by itsroh3it** [comment]
@Jyotishmoy12 

npm install --save-dev hardhat @nomiclabs/hardhat-waffle ethereum-waffle chai @nomiclabs/hardhat-ethers ethers

**Comment by Jyotishmoy12** [comment]
Thank you so much 😄
