### ISSUE TITLE
Uncaught (in promise) Error: No ethereum object     at sendTransaction (TransactionContext.jsx:139:13)

### ISSUE THREAD

**Issue by Jyotishmoy12** [adrianhajdin/project_web3.0#70]
plss help me in this issue.... plssssssssssss

**Comment by ImranKhanIMS** [comment]
> plss help me in this issue.... plssssssssssss

same issue did you resolve it if yes how?

**Comment by Jyotishmoy12** [comment]
> 

Hey it was actually not an error for me I was just dumb.. You should have a minimum ethereum amount from which you want to send to the other account...Hope this helps..

**Comment by ImranKhanIMS** [comment]
actually, I'm using Goerli testnet and I follow the tutorial 100% same but I got the below issue when I click on the send button

![image](https://user-images.githubusercontent.com/73417382/231227449-46272fa2-4e3b-4817-a171-b6d9c947552e.png)

![image](https://user-images.githubusercontent.com/73417382/231227600-482eb25f-f955-4fce-a18f-00b11870e8ec.png)

![image](https://user-images.githubusercontent.com/73417382/231227765-3e4147b7-05a0-470b-95f2-d22235e06f03.png)


if you know the solutions kindly help me please

**Comment by Jyotishmoy12** [comment]
> actually, I'm using Goerli testnet and I follow the tutorial 100% same but I got the below issue when I click on the send button
> 
> ![image](https://user-images.githubusercontent.com/73417382/231227449-46272fa2-4e3b-4817-a171-b6d9c947552e.png)
> 
> ![image](https://user-images.githubusercontent.com/73417382/231227600-482eb25f-f955-4fce-a18f-00b11870e8ec.png)
> 
> ![image](https://user-images.githubusercontent.com/73417382/231227765-3e4147b7-05a0-470b-95f2-d22235e06f03.png)
> 
> if you know the solutions kindly help me please

You also need to create an env file for api to work... checkout my code base
