### ISSUE TITLE
adding logo

### ISSUE THREAD

**Issue by sakurafn1** [adrianhajdin/project_web3.0#88]
adding the logo makes a bug even after i instaled the package pls help

**Comment by couragebernard** [comment]
There will be something wrong with the file path then. If you can send your code tree, I might be able to help with the correct path.

**Comment by sakurafn1** [comment]
> There will be something wrong with the file path then. If you can send your code tree, I might be able to help with the correct path.

Ya I got it fixed I just had to try different paths thank you
