### ISSUE TITLE
Uncaught (in promise) Error: No ethereum object at sendTransaction (TransactionContext.jsx)

### ISSUE THREAD

**Issue by ImranKhanIMS** [adrianhajdin/project_web3.0#94]
I'm using Goerli testnet and I follow the tutorial 100% same but I got the below issue when I click on the send button

![image](https://user-images.githubusercontent.com/73417382/231227449-46272fa2-4e3b-4817-a171-b6d9c947552e.png)

![image](https://user-images.githubusercontent.com/73417382/231227600-482eb25f-f955-4fce-a18f-00b11870e8ec.png)

![image](https://user-images.githubusercontent.com/73417382/231227765-3e4147b7-05a0-470b-95f2-d22235e06f03.png)

if anyone know the solutions kindly help me, please

**Comment by SouhaRebai** [comment]
Hello there I had the same exact error. It was fixed when i downgraded ethers version like so:
-npm uninstall ethers
-npm i -S ethers@5.7.2
reference:
https://ethereum.stackexchange.com/questions/144315/nextjs-13-and-ethers-properties-of-undefined-reading-web3provider

Good luck!

**Comment by Gitesh2435** [comment]
Thanks @SouhaRebai this solution works.
